baseURL = "https://agsdot.github.io/test_ssb/"
languageCode = "en-us"
title = "Your Site Title"
#theme = "your-hugo-theme-name"

[params]
  author = "Jonathan"

[markup]
  defaultMarkdownHandler = "goldmark"

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"

[permalinks]
  post = "/:year/:month/:day/:title/"

[build]
  publishDir = "public"
